### ISSUE TITLE
let private keys being stored as a string inside an Ansible vault 

### ISSUE THREAD

**Issue by drzraf** [felixfontein/acme-certificate#1]
ansible-vault lets store private data inside an encrypted file.
This could provide helpful for git-managed playbook where private keys must be kept secretly.
Using `copy: contents=` lets create the key file from a vault-protected variable.

**Comment by felixfontein** [comment]
Hi drzraf, thank you for your suggestions!

There are two types of private keys in use:
 - the private key for the Let's Encrypt account, and
 - the private keys for the certificates.

The private key for the Let's Encrypt account is needed in many of the steps, but it never changes. Thus it can easily be stored in a vault variable. The hard part is passing it to the programs; passing it as a command line argument is bad (other programs running in the machine could see it), and writing it to disk is also bad. So the best choice would be passing it in via stdin. Do you have an idea how to do this?
Also, we'd have to make sure that the key isn't written to disk temporarily by ansible; when executing something on a remote machine, ansible copies the module's Python file with all specified data inside to the target machine. I'm not sure what exactly happens when running a local action, if it also creates the same file locally to execute it, or if it does run the module directly and passing the data internally so that it stays inside Python. If it would write the data to disk, this would be terrible. (That's something I never looked cosely at, so I really don't know what happens in this case.)

The private certificate keys are more tricky, since some of the commands (`issue-tls-certs-newkey`, `create-tls-keys`) generate the keys and thus need to update their values. If the source of the key is a variable in an encrypted config file, this config file needs to be updated. I don't see how to do this in a nice way. Of course, one could expect the user to manually copy the generated key file's contents into the encrypted configuration and then to safely delete the key file on disk, but that's a lot of unnecessary work and the key was written to disk temporarily. (And someone might accidently check the key file in.)

The only other step needing the private certificate key is `create-csr.yml`, which needs to sign the CSR with the private key. This needs to be done when the domain list changes or when the private key changes. Here we could pass the private cert key via stdin (as the Let's Encrypt account key isn't needed in this step), but this again opens the same questions as above.

For now, it's probably best to store the keys not inside your global GIT/... repository, but inside a special configuration one which isn't public. Or put the whole key generation/to server uploading part of ansible into its own private repository.

**Comment by drzraf** [comment]
On Wed, May 11, 2016 at 11:04:16PM -0700, Felix Fontein wrote:
> So the best choice would be passing it in via stdin. Do you have an
> idea how to do this?

Not really, but: https://github.com/diafygi/acme-tiny/issues/124

> The private certificate keys are more tricky, since some of the
> commands (`issue-tls-certs-newkey`, `create-tls-keys`) generate the
> keys

I was not clear enough, I thought about providing keys myself (using
vault-encrypted variable) so that this step¹ which deals with sensible
data becomes optional.

¹ ``acme_compact.py gen-key`` inside ``create-key.yml``

We are left with:
``acme_compact.py gen-csr`` inside ``create-key.yml``
Which is where variable would be used (and ideally, stdin)

> Here we could pass the private cert key via stdin (as the Let's
> Encrypt account key isn't needed in this step), but this again opens
> the same questions as above.

Note that such a command:
``$ openssl req -new -sha256 -key <(cat my.key) -subj "/" -reqexts SAN -config <(cat openssl.conf; printf "[SAN]\nsubjectAltName=DNS:bla.foo.com")``
is valid using bash (and name file descriptor), as is (more interestingly):
``$ cat my.key | openssl req -new -sha256 -key /dev/stdin -subj "/" -reqexts SAN -config <(cat openssl.conf; printf "[SAN]\nsubjectAltName=DNS:bla.foo.com")``
OpenSSL can read key from stdin.

Since the process is the following:
``acme_compact.py gen-csr`` => ``acme_compact.py _gen_csr`` => ``acme_lib.generate_csr`` which does
``_run_openssl(['req', '-new', '-sha256', '-key', key_filename, '-subj', '/', '-config', config_filename])``
Private cert key is only used once, so stdin is a realistic option.

(Using Python I/O it may even be possible to pass config as a named pipe rather than using temporary file, but that's another topic)

**Comment by felixfontein** [comment]
Reading from stdin in Python is not the problem. The problem is: how do I tell ansible to send the key to stdin of the Python program? Especially, with making sure that the private key is not written to disk while this happens (Ansible could do that, depending on how that part of Ansible is implemented).

Modifying acme_compact to read from stdin should be no problem.

**Comment by drzraf** [comment]
For reference:
Actual:
```
local_action: shell python roles/letsencrypt/code/acme_compact.py gen-csr --key "keys/{{ domains[0] }}.key" --csr "keys/{{ domains[0] }}.csr" --domains "{{ ','.join(domains) }}"
run_once: True
```

stdin-based:
```
local_action: echo "{{cert_private_key}}" | shell python roles/letsencrypt/code/acme_compact.py gen-csr --key - --csr "keys/{{ domains[0] }}.csr" --domains "{{ ','.join(domains) }}"
run_once: True
no_log: True
```

**Comment by felixfontein** [comment]
Wait. `shell` is the Ansible role which was executed locally here. So mustn't this me `local_action: shell echo "{{ cert_private_key}}" | python ...`?

But that will probably show the private key to every user on that machine running `ps aux` at the right moment.

**Comment by drzraf** [comment]
You're right about the playbook. I just edited to fix it.
About security you're right too... but I'd not be that worried :
* granted, this is less secure than environment variable
* but this is run on adminsys machine where vault.yml , keys/ & co are present. It must be secure in the first place
* the ``echo`` process last a couple of milli-seconds, ``ps faux`` does not show the whole pipeline, for example ``echo secret|sleep 5`` will just show the ``sleep`` 99.99999% of the time it takes to proceed

For the long-term fix: https://github.com/ansible/ansible-modules-core/pull/2306

**Comment by felixfontein** [comment]
Ok, so let's assume we have the long-term fix. But there's still a problem: ansible will write the command module with the arguments which have to be run to disk (in `~/.ansible/tmp/ansible-tmp/xxxxxx/command` or `.../shell`), executes that Python script, and then deletes that file (if `ANSIBLE_KEEP_REMOTE_FILES=1` is not defined). This means that the private key will be temporarily written to disk while NOT being encrypted.

And yes, even if this is written to disk only for a few milliseconds, a skilled attacker could use it (assuming he can get access to `~/.ansible`, which is a lot harder than using `/proc` to catch `echo` arguments).

**Comment by drzraf** [comment]
> there's still a problem: ansible will write the command module with the arguments which have to be run to disk (in `~/.ansible/tmp/ansible-tmp/xxxxxx/command` or `.../shell`), executes that Python script, and then deletes that file (if `ANSIBLE_KEEP_REMOTE_FILES=1` is not defined). This means that the private key will be temporarily written to disk while NOT being encrypted.

1) is it the case with no_log = True?
2) I'm not sure this is any better (or worst) than writing them (in cleartext
   too) in keys/, is it?

I still can see how more practical it is to store them in a vault shared
with the team through the git repository, but I've too agree that it
won't make the whole thing any secure ATM.

**Comment by felixfontein** [comment]
1) no_log = True won't help, as this is not about log output, but the way in which Ansible actually works (executes tasks). It always does so by writing a Python script to disk and executing it. The Python script is essentially the command module enhanced by inserting the arguments. So, no, you cannot prevent Ansible from writing this to disk.

2) Depends on your point of view ;) For me, it is better as I at least always know where the private key is stored in plaintext, instead of it being written to disk in hidden places by Ansible which I sometimes forget about.

A better alternative would probably to put the `keys/` subdirectory in an encrypted volume which is only unlocked when you need to run the playbook, for example with ecryptfs. You can then also check the encrypted container into git.

**Comment by felixfontein** [comment]
I started playing around with at least allowing passing the private keys to `acme_compact` via stdin. While this works fine for CSR generation (see https://github.com/felixfontein/acme-compact/commit/244eac5240f9f3e57abd8b3f0c37905b58437642), it does not and probably will never work for the Let's Encrypt account key: the problem is that for talking to the Let's Encrypt servers, you need to sign everything with the account key. This is done with `openssl dgst -sha256 -sign <account key filename>" and passing the content to be signed via stdin. I doubt that you can get `openssl dgst` to read both the key as well as the message to sign from stdin.

To work around this, we have to either try something like writing the message to be signed to disk and pass the key via stdin, or use something else than OpenSSL. Both of these require massive changes. If you really want that, feel free to implement it in some way.

**Comment by drzraf** [comment]
For historical reference https://github.com/ansible/ansible/pull/27335
(although Ansible 2.4 core contains a letsencrypt module anyway)

**Comment by felixfontein** [comment]
I don't think the `letsencrypt` module supports this: it requires the account key to be on disk ([docs](https://docs.ansible.com/ansible/latest/letsencrypt_module.html)).

**Comment by drzraf** [comment]
https://github.com/ansible/ansible/pull/32948

**Comment by felixfontein** [comment]
Ah, good!

Unfortunately, that solution is simply writing the key onto disk and deletes the file afterwards, which could be a security problem. Also, the module file containing the (unprotected) account key is written to disk on the machine (at least when running the module on a remote server; I don't know what happens for `local_action`). So from a security perspective, this is far from optimal.

**Comment by drzraf** [comment]
Sadly I do agree on both point.
The state-of-stdin for Ansible-internals is still greatly described by this comment
https://github.com/ansible/ansible/pull/27335#issuecomment-322643039
From a pure `letsencrypt` PoV, only changes to the `openssl` binary could solve the issue (or maybe some file-descriptor black-magic from the caller)

**Comment by felixfontein** [comment]
Since last year or so, the `acme_certificate` (used to be `letsencrypt`) module supports a `cryptography` backend, which doesn't require the key to be written to disk.

What's still true, though, is that the key will potentially be written to disk while transferring the module options to the remote host.

**Comment by felixfontein** [comment]
I've implemented that in https://github.com/felixfontein/ansible-acme/.

**Comment by drzraf** [comment]
Some of the `stdin` issues have been fixed since then (`stdin` parameter and `stdin_add_newline`), but even in latest Ansible version, stdin is still stored on-disk as any other parameter.
